language: R
dist: trusty
sudo: required
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

pandoc_version: 2.1.1

before_install:
- mkdir ~/.R
- cp Makevars ~/.R
- npm install netlify-cli -g
- sudo apt-get install pdftk
- sudo apt-get install texlive-latex-base
- sudo apt-get install texlive-fonts-recommended
- sudo apt-get install texlive-fonts-extra
- sudo apt-get install texlive-latex-extra
- sudo apt-get install texlive-xetex
- sudo apt-get install fonts-inconsolata -y
- sudo fc-cache -fv

#- sudo apt-get install texlive-latex-base
#- sudo apt-get install texlive-fonts-recommended
#- sudo apt-get install texlive-latex-extra
#- sudo apt-get install texlive-xetex
#- sudo apt-get install xzdec
#- sudo tlmgr init-usertree
#- sudo tlmgr update --all
#- sudo tlmgr install lm-math unicode-math filehook


script:
- Rscript -e "install.packages('tinytex')"
- Rscript -e "tinytex::tlmgr_install(c('lm-math', 'unicode-math', 'filehook'))"
- Rscript -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::pdf_book")'
- cp adv-r_cover.pdf _book
- cd _book
- pdftk _main.pdf cat 2-r3 output adv-r_ori.pdf
- pdftk adv-r_cover.pdf adv-r_ori.pdf cat output adv-r.pdf && rm -r adv-r_*.pdf
- cd -

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: _book # Book output directory
  on:
    branch: master
